Description: >
  Project 5 stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
  InstanceNamePrefix:
    Description: Instance name.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Secgroup-${InstanceNamePrefix}-${ID}
      GroupDescription: Allow port 22 and port 80.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: devopsproject5
      ImageId: ami-068663a3c619dd892 
      #ImageId: ami-04a0ae173da5807d3
      Tags:
        - Key: Name
          Value: !Sub ${InstanceNamePrefix}-${ID}
