apiVersion: v1
kind: Service
metadata:
  name: eks-webserver
  namespace: eks-webserver
  labels:
    app: eks-webserver
spec:
  selector:
    app: eks-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80